### ISSUE TITLE
Extension not supported: Some("yml")

### ISSUE THREAD

**Issue by kthkaya** [chevdor/tera-cli#6]
Hi,

I am getting the following error when I pass the yml context data as a file and not stdin

tera -t rules\namingConvention.tera convention.yml
thread 'main' panicked at 'Extension not supported: Some("yml")', src\wrapped_context.rs:167:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Any ideas?

Thanks

**Comment by chevdor** [comment]
Hello @kthkaya,
The issue you are running into is that currently, only the following is supported: `json`, `toml`, `yaml`. Notice it is `yaml` and not `yml`. So renaming your file to `.yaml` should solve your issue.

I am closing the issue but feel free to reopen if that does not work or if you think that `yml` should also be supported. A PR would be very welcome if that's the case.

**Comment by kthkaya** [comment]
Thanks!
